### ISSUE TITLE
OSX test-client.py hangs

### ISSUE THREAD

**Issue by TiborUdvari** [dictation-toolbox/aenea#127]
I'm trying to setup `aenea` server on `OSX El Capitan`. When I try to run `server_osx.py` followed by `test-client.py` I get aAB printed to my terminal after which the script seems to hang all while seemingly keeping the `Shift` key pressed all the time. 

Is this a known issue, how good is *osx* support for `aenea`. It is not really clear from the `README` files. 

PS: Great project, I think it this impacts/helps a lot of people in a meaningful way. I hope it to include me as well in the near future.

**Comment by calmofthestorm** [comment]
All the OS X support was contributed by people with macs. My understanding is it did work at one point, but I'm unable to offer any help directly since I don't have any OS X machines.

Some debugging thoughts: you could try connecting to the server directly from a command line Python (take a look at the test client for how to do this) and see if it also causes issues when you send RPCs directly. I can try to help if it's an issue in the client or server, but most likely it's in the Applescript integration.

**Comment by TiborUdvari** [comment]
Thanks for the info. I will look into it myself. I must say it's a little challenging when not really familiar with the system.

**Comment by dylan-chong** [comment]
@TiborUdvari Did you find a solution?
