### ISSUE TITLE
Has anyone tried a newer version of dragon (13, 14, etc)

### ISSUE THREAD

**Issue by dylan-chong** [dictation-toolbox/aenea#174]
There might be some accuracy and speed benefits of using a newer version of dragon

**Comment by LexiconCode** [comment]
Greetings,
I've been using Dragon NaturallySpeaking since version 9. I noticed a big jump in performance in recognition latency and accuracy going from version v12 to v13 and a marginal jump to v15. One aspect I do like about v15 as I can have multiple audio sources in one user profile. To get in-depth an analysis read [Knowbrainer DNS Reviews](www.knowbrainer.com/index.cfm/wiki/dragon-15-review). Old DNS versions reviews can be found on their [Wiki](http://www.knowbrainer.com/index.cfm/wiki/)

Overall my personal recommendation is if you're using anything less than DNS 13 it's time for an upgrade. DNS 15 home just was released In the last 6 months.

**Comment by dylan-chong** [comment]
Thank you! I'll be definitely willing to try out version 13. Have you tried version 13 with Aenea?

**Comment by LexiconCode** [comment]
I currently don't have Aenea set up at the moment. Although I will soon as I'm working to help implement Aenea Support in the [Caster](https://github.com/synkarius/caster) project. I know a number of people that use Aenea with DNS versions 13 through 15 without issues. Aenea set up seems to be pretty brittle but that separate from the speech recognition engine.

**Comment by dylan-chong** [comment]
Sounds good. Do you know of anyone who i talk to in case i encounter problems?

**Comment by LexiconCode** [comment]
Sure, I'm not an expert but we do have some helpful people [Caster Gitter Chat Channel](https://gitter.im/synkarius/caster?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Make sure to get the latest [Natlink](https://sourceforge.net/projects/natlink/files/natlink/natlinktest4.1/) and utilize community fork of [Dragonfly](https://github.com/Danesprite/dragonfly). after uninstalling  t4ngo/dragonfly via pip.

**Comment by dylan-chong** [comment]
Thanks. Am using dragonfly2 package. 

I plan on updating on the documentation for setting up this project. Trying out dragon thirteen will be a good opportunity to do this. I will get in touch with them, and update my progress here!

**Comment by calmofthestorm** [comment]
It'd be awesome to get Aenea working with Caster, I'm glad to hear you're working on that!

**Comment by dylan-chong** [comment]
It appears dragon 13 is working well
